// Code generated by qtc from "articles.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package blog

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (articles *Articles) StreamArticles(qw422016 *qt422016.Writer) {
	qw422016.N().S(`<div class="articles">

<section id="article-0" class="mt-4"></section>

`)
	for articles.Next() {
		qw422016.N().S(`
`)
		articles.article.StreamArticle(qw422016)
		qw422016.N().S(`
`)
	}
	qw422016.N().S(`

</div>
`)
}

func (articles *Articles) WriteArticles(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	articles.StreamArticles(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (articles *Articles) Articles() string {
	qb422016 := qt422016.AcquireByteBuffer()
	articles.WriteArticles(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
