// Code generated by qtc from "edit.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package blog

import "bytes"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (article *Article) StreamEdit(qw422016 *qt422016.Writer) {
	if article.article_id != 0 {
		article.StreamArticle(qw422016)
	}
	qw422016.N().S(`

<form id="article-form-`)
	qw422016.N().D(article.article_id)
	qw422016.N().S(`" action="/edit/`)
	qw422016.N().D(article.article_id)
	qw422016.N().S(`" method="post" autocomplete="off" class="article-form bg-light mt-3 ms-4 me-3 p-3">

<div class="form-floating">
<input id="title-`)
	qw422016.N().D(article.article_id)
	qw422016.N().S(`" type="text" name="title" class="form-control" value="`)
	qw422016.E().Z(article.title)
	qw422016.N().S(`" autofocus>
<label for="title-`)
	qw422016.N().D(article.article_id)
	qw422016.N().S(`">Title</label>
</div>

<div class="form-floating mt-3">
<textarea id="body-`)
	qw422016.N().D(article.article_id)
	qw422016.N().S(`" name="body" class="form-control" style="height: 16em">`)
	qw422016.E().Z(article.body)
	qw422016.N().S(`</textarea>
<label for="body-`)
	qw422016.N().D(article.article_id)
	qw422016.N().S(`">Body</label>
</div>

<div class="form-floating mt-3">
<input id="tags-`)
	qw422016.N().D(article.article_id)
	qw422016.N().S(`" type="text" name="tags" class="form-control" value="`)
	qw422016.E().Z(bytes.Join(article.tags, []byte(", ")))
	qw422016.N().S(`">
<label for="tags-`)
	qw422016.N().D(article.article_id)
	qw422016.N().S(`">Tags</label>
</div>

<div class="form-check mt-3">
<input id="public-`)
	qw422016.N().D(article.article_id)
	qw422016.N().S(`" type="checkbox" name="public"`)
	if article.public {
		qw422016.N().S(` checked`)
	}
	qw422016.N().S(`>
<label for="public-`)
	qw422016.N().D(article.article_id)
	qw422016.N().S(`">Public</label>
</div>

<div class="mt-3 d-flex justify-content-between">
<button type="submit" class="btn btn-outline-primary">Save</button>
<button id="cancel-`)
	qw422016.N().D(article.article_id)
	qw422016.N().S(`" type="button" class="cancel-edit btn btn-outline-danger">Cancel</button>
</div>

</form>
`)
}

func (article *Article) WriteEdit(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	article.StreamEdit(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (article *Article) Edit() string {
	qb422016 := qt422016.AcquireByteBuffer()
	article.WriteEdit(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
